#################
### AUTOSTART ###
#################

#exec-once = hyprpaper
#exec-once = wl-paste --watch cliphist store &
exec-once = sh ~/scripts/xdg.sh
exec-once = hypridle
exec-once = swww-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = sh ~/scripts/waybar/launch.sh
exec-once = swaync
exec-once = nm-applet
exec-once = webcord -m
exec-once = /usr/lib/polkit-kde-authentication-agent-1
